/*
 * QR encoder tests.
 *
 * The encoder is hand-rolled, so "it looks like a QR code" is not evidence.
 * A wrong Reed-Solomon remainder, a wrong data-placement order or a wrong
 * mask all still produce something that looks like a QR code and scans to
 * garbage — which, for a payment QR, means money sent to the wrong place.
 *
 * So the primary test compares the matrix module-for-module against fixtures
 * generated by segno (scripts/gen-qr-fixtures.py), with the mask pinned so
 * the comparison isolates encoding from mask selection.
 *
 * Run:  npm test
 */
'use strict';

const test = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');

const QR = require('../qr.js');

const FIXTURES = JSON.parse(
  fs.readFileSync(path.join(__dirname, 'fixtures', 'qr-segno.json'), 'utf8')
);

function ourMatrix(text, level, mask) {
  const qr = QR.encode(text, { level, mask });
  return qr.modules.map((row) => row.map((v) => (v ? '1' : '0')).join(''));
}

function diffCount(a, b) {
  let n = 0;
  for (let y = 0; y < a.length; y++) {
    for (let x = 0; x < a[y].length; x++) {
      if (a[y][x] !== b[y][x]) n++;
    }
  }
  return n;
}

// ── the real test: exact agreement with the reference implementation ───────

for (const fx of FIXTURES) {
  test(`matches segno exactly for every mask: ${fx.name}`, () => {
    for (let mask = 0; mask < 8; mask++) {
      const expected = fx.masks[String(mask)];
      const actual = ourMatrix(fx.text, fx.level, mask);
      assert.equal(actual.length, expected.length,
        `${fx.name} mask ${mask}: size mismatch`);
      const d = diffCount(actual, expected);
      assert.equal(d, 0,
        `${fx.name} mask ${mask}: ${d} module(s) differ from segno`);
    }
  });
}

test('picks the same version as segno', () => {
  for (const fx of FIXTURES) {
    const qr = QR.encode(fx.text, { level: fx.level });
    assert.equal(qr.version, fx.version, `${fx.name}: version`);
    assert.equal(qr.size, fx.size, `${fx.name}: size`);
  }
});

test('mask selection stays within the valid range and scores sanely', () => {
  // Our penalty implementation need not match segno's tie-breaking, but it
  // must pick a mask whose encoding is valid, and must not pick one that
  // scores worse than another by a wide margin.
  for (const fx of FIXTURES) {
    const qr = QR.encode(fx.text, { level: fx.level });
    assert.ok(qr.size > 0, `${fx.name}: produced a symbol`);
    const auto = QR.encode(fx.text, { level: fx.level });
    const chosen = auto.modules;
    // The chosen mask must round-trip through the pinned-mask path.
    let matchedSomeMask = false;
    for (let mask = 0; mask < 8; mask++) {
      const pinned = QR.encode(fx.text, { level: fx.level, mask });
      if (diffCount(chosen, pinned.modules) === 0) matchedSomeMask = true;
    }
    assert.ok(matchedSomeMask,
      `${fx.name}: auto-selected matrix matches no valid pinned mask`);
  }
});

// ── structure ──────────────────────────────────────────────────────────────

test('finder patterns sit in the three corners', () => {
  const qr = QR.encode('solana:9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin', { level: 'L' });
  const m = qr.modules;
  const n = qr.size;
  const corners = [[0, 0], [n - 7, 0], [0, n - 7]];
  for (const [cx, cy] of corners) {
    for (let y = 0; y < 7; y++) {
      for (let x = 0; x < 7; x++) {
        const border = x === 0 || y === 0 || x === 6 || y === 6;
        const core = x >= 2 && x <= 4 && y >= 2 && y <= 4;
        const expected = border || core ? 1 : 0;
        assert.equal(m[cy + y][cx + x], expected,
          `finder at ${cx},${cy} offset ${x},${y}`);
      }
    }
  }
});

test('the always-dark module is set', () => {
  const qr = QR.encode('PAYTAG', { level: 'L' });
  assert.equal(qr.modules[qr.size - 8][8], 1, 'dark module must be set');
});

test('timing patterns alternate', () => {
  const qr = QR.encode('solana:9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin', { level: 'L' });
  for (let i = 8; i < qr.size - 8; i++) {
    assert.equal(qr.modules[6][i], i % 2 === 0 ? 1 : 0, `row timing at ${i}`);
    assert.equal(qr.modules[i][6], i % 2 === 0 ? 1 : 0, `col timing at ${i}`);
  }
});

// ── behaviour ──────────────────────────────────────────────────────────────

test('a longer payload needs a larger version', () => {
  const small = QR.encode('PAYTAG', { level: 'L' });
  const big = QR.encode('x'.repeat(300), { level: 'L' });
  assert.ok(big.version > small.version,
    `expected growth, got v${small.version} -> v${big.version}`);
});

test('version 7 and up emit version information', () => {
  // 200 bytes forces version >= 9 at level L.
  const qr = QR.encode('y'.repeat(200), { level: 'L' });
  assert.ok(qr.version >= 7, `expected v7+, got v${qr.version}`);
  // The version-info blocks are 3x6 in the top-right and bottom-left. If they
  // were left blank the symbol would be unreadable; check they are populated.
  let setTopRight = 0;
  for (let y = 0; y < 6; y++) {
    for (let x = qr.size - 11; x < qr.size - 8; x++) {
      if (qr.modules[y][x]) setTopRight++;
    }
  }
  assert.ok(setTopRight > 0, 'version info block is empty');
});

test('UTF-8 labels encode without throwing and stay in range', () => {
  const qr = QR.encode('solana:9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin?label=caf\u00e9',
    { level: 'L' });
  assert.ok(qr.size > 0);
});

test('oversized input at the strictest level falls back rather than throwing', () => {
  // Too long for level L entirely: must throw, not silently truncate.
  assert.throws(() => QR.encode('z'.repeat(3000), { level: 'L' }), /too long/i);
});

// ── rendering ──────────────────────────────────────────────────────────────

test('SVG output has a quiet zone and the right dimensions', () => {
  const svg = QR.toSvg('PAYTAG', { scale: 4, border: 4 });
  const qr = QR.encode('PAYTAG', { level: 'L' });
  const expected = (qr.size + 8) * 4;
  assert.match(svg, new RegExp('width="' + expected + '"'));
  assert.match(svg, new RegExp('height="' + expected + '"'));
  assert.match(svg, /role="img"/);
  assert.match(svg, /fill="#000000"/, 'modules drawn in black');
});

test('SVG contains no unescaped markup from the payload', () => {
  const svg = QR.toSvg('solana:abc?label=<script>', {});
  assert.doesNotMatch(svg, /<script>/, 'payload must not reach the SVG verbatim');
});

test('ASCII rendering has the expected line count', () => {
  const ascii = QR.toAscii('PAYTAG', { level: 'L' });
  const qr = QR.encode('PAYTAG', { level: 'L' });
  assert.equal(ascii.split('\n').length, qr.size);
});
